In [1]:
pip install requests

Collecting requestsNote: you may need to restart the kernel to use updated packages.

  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 idna-3.10 requests-2.32.3 urllib3-2.2.3

In [3]:
BASE_URL = "saiapi.corp.globant.com"

In [4]:
API_TOKEN = "mentor_match_ap_uw1uQE2a5V546cI_4XqoVylHaNMcdFFh72R9Fb1oFzBSZdE6KPFsF4W6JBrjen3qsvD97_8FBjXMf672tsN_Jr3daWaEvJrTj63_L9nmbXD0BMf4s0VgL_hGoYBwyaatja08G1dfKdKJYBrP6ia_9l9cBggnYcfWFUJofIK8_fM="

In [7]:
import requests

# Definir las variables
#BASE_URL = "https://api.saia.ai"  # Cambia esto por tu URL base
#API_TOKEN = "tu_token_api_aqui"    # Reemplaza con tu token de API

# Función para hacer una solicitud a la API
def hacer_solicitud(endpoint, datos=None):
    headers = {
        "Authorization": f"Bearer {API_TOKEN}",
        "Content-Type": "application/json"
    }
    
    url = f"{BASE_URL}"
    
    response = requests.post(url, headers=headers, json=datos)
    
    if response.status_code == 200:
        return response.json()  # Retorna la respuesta en formato JSON
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Ejemplo de uso: reemplaza 'tu_endpoint' con el endpoint específico que deseas consultar
datos_a_enviar = {
    # Incluye aquí los datos que necesites enviar a la API
}

resultado = hacer_solicitud("", datos_a_enviar)

if resultado:
    print("Respuesta de la API:", resultado)

MissingSchema: Invalid URL 'saiapi.corp.globant.com': No scheme supplied. Perhaps you meant https://saiapi.corp.globant.com?

Usando Genexus AI

In [8]:
import requests

def hacer_solicitud(endpoint, datos=None):
    headers = {
        "Authorization": f"Bearer {API_TOKEN}",
        "Content-Type": "application/json"
    }
    
    url = f"{BASE_URL}/{endpoint}"
    
    response = requests.post(url, headers=headers, json=datos)
    
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

In [9]:
mentores = [
    {"nombre": "Mentor A", "habilidades": {"data pipeline": 4, "self-motivation": 5}},
    {"nombre": "Mentor B", "habilidades": {"data pipeline": 3, "self-motivation": 4}},
]

In [10]:
def filtrar_mentores(habilidades_deseadas):
    habilidades_deseadas = habilidades_deseadas.split(", ")
    mentores_filtrados = []
    
    for mentor in mentores:
        puntaje = sum(mentor["habilidades"].get(habilidad, 0) for habilidad in habilidades_deseadas)
        if puntaje >= len(habilidades_deseadas) * 3:  # Al menos un puntaje promedio de 3
            mentores_filtrados.append(mentor["nombre"])
    
    return mentores_filtrados

# Ejemplo de uso
habilidades_deseadas = "data pipeline, self-motivation"
mentores_recomendados = filtrar_mentores(habilidades_deseadas)
print("Mentores recomendados:", mentores_recomendados)

Mentores recomendados: ['Mentor A', 'Mentor B']

In [11]:
# Endpoint específico para obtener recomendaciones
endpoint = "recomendaciones"  # Cambia esto por el endpoint correcto

# Datos que deseas enviar a la API (por ejemplo, habilidades deseadas)
datos_a_enviar = {
    "habilidades": habilidades_deseadas
}

# Realiza la solicitud a la API
resultado_api = hacer_solicitud(endpoint, datos_a_enviar)

if resultado_api:
    print("Recomendaciones desde GeneXus AI:", resultado_api)

MissingSchema: Invalid URL 'saiapi.corp.globant.com/recomendaciones': No scheme supplied. Perhaps you meant https://saiapi.corp.globant.com/recomendaciones?

In [12]:
def filtrar_mentores(habilidades_deseadas, mentores):
    habilidades_deseadas = habilidades_deseadas.split(", ")
    mentores_filtrados = []
    
    for mentor in mentores:
        puntaje = sum(mentor["habilidades"].get(habilidad.strip(), 0) for habilidad in habilidades_deseadas)
        if puntaje >= len(habilidades_deseadas) * 3:  # Al menos un puntaje promedio de 3
            mentores_filtrados.append(mentor["nombre"])
    
    return mentores_filtrados

# Filtrar los mentores obtenidos
mentores_recomendados = filtrar_mentores(habilidades_deseadas, mentores)
print("Mentores recomendados:", mentores_recomendados)

Mentores recomendados: ['Mentor A', 'Mentor B']

Entrenando al modelo Sistema Recomendador -  Slope One metodo latentes ...

In [14]:
pip install scikit-surprise

Collecting scikit-surprise
  Using cached scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting joblib>=1.2.0 (from scikit-surprise)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (2.1.3)
Collecting scipy>=1.6.0 (from scikit-surprise)
  Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml): started
  Building wheel for scikit-surprise (pyproject.toml): finished with status 'error'
Failed to build scikit-surprise
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Building wheel for scikit-surprise (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-312\surprise
      copying surprise\accuracy.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\builtin_datasets.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dataset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dump.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\reader.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\trainset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\utils.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__init__.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__main__.py -> build\lib.win-amd64-cpython-312\surprise
      creating build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\search.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\split.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\validation.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\__init__.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      creating build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running egg_info
      writing scikit_surprise.egg-info\PKG-INFO
      writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
      writing entry points to scikit_surprise.egg-info\entry_points.txt
      writing requirements to scikit_surprise.egg-info\requires.txt
      writing top-level names to scikit_surprise.egg-info\top_level.txt
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.so' found under directory 'surprise'
      adding license file 'LICENSE.md'
      writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-77llepb4\overlay\Lib\site-packages\setuptools\command\build_py.py:212: _Warning: Package 'surprise.prediction_algorithms' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'surprise.prediction_algorithms' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'surprise.prediction_algorithms' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'surprise.prediction_algorithms' to be distributed and are
              already explicitly excluding 'surprise.prediction_algorithms' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying surprise\similarities.c -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\similarities.pyx -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running build_ext
      building 'surprise.similarities' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-surprise
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-surprise)

In [5]:
pip install scikit-suprise==1.1.4

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement scikit-suprise==1.1.4 (from versions: none)
ERROR: No matching distribution found for scikit-suprise==1.1.4

In [7]:
pip install --pre scikit-image

Collecting scikit-imageNote: you may need to restart the kernel to use updated packages.

  Downloading scikit_image-0.25.0rc1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.24 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-image) (2.1.3)
Collecting scipy>=1.10 (from scikit-image)
  Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting networkx>=3.0 (from scikit-image)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting pillow>=9.1 (from scikit-image)
  Downloading pillow-11.0.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting imageio!=2.35.0,>=2.33 (from scikit-image)
  Downloading imageio-2.36.0-py3-none-any.whl.metadata (5.2 kB)
Collecting tifffile>=2022.8.12 (from scikit-image)
  Downloading tifffile-2024.9.20-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: packaging>=21 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-image) (24.2)
Collecting lazy-loader>=0.4 (from scikit-image)
  Downloading lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Downloading scikit_image-0.25.0rc1-cp312-cp312-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 2.4 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.9 MB 3.2 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.9 MB 3.5 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.9 MB 3.3 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.9 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.9 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.9 MB 3.4 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.9 MB 3.4 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.9 MB 3.4 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.9 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 7.1/12.9 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.9 MB 3.1 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.9 MB 3.1 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.9 MB 3.1 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.9 MB 2.9 MB/s eta 0:00:02
   ------------------------------ --------- 10.0/12.9 MB 3.0 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.9 MB 3.1 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 3.2 MB/s eta 0:00:00
Downloading imageio-2.36.0-py3-none-any.whl (315 kB)
Downloading lazy_loader-0.4-py3-none-any.whl (12 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------ --------------------- 0.8/1.7 MB 4.2 MB/s eta 0:00:01
   ------------------------------------ --- 1.6/1.7 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 3.9 MB/s eta 0:00:00
Downloading pillow-11.0.0-cp312-cp312-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ------------ --------------------------- 0.8/2.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------- ----------- 1.8/2.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 4.3 MB/s eta 0:00:00
Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
Downloading tifffile-2024.9.20-py3-none-any.whl (228 kB)
Installing collected packages: tifffile, scipy, pillow, networkx, lazy-loader, imageio, scikit-image
Successfully installed imageio-2.36.0 lazy-loader-0.4 networkx-3.4.2 pillow-11.0.0 scikit-image-0.25.0rc1 scipy-1.14.1 tifffile-2024.9.20

In [9]:
pip --version

pip 24.3.1 from c:\Users\b.vivanco\Desktop\dev\globant_ai\mvp-env\Lib\site-packages\pip (python 3.12)

Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install joblib numpy scipy

Collecting joblib
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (2.1.3)
Requirement already satisfied: scipy in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (1.14.1)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Installing collected packages: joblib
Successfully installed joblib-1.4.2

In [5]:
!pip install scikit-surprise

Collecting scikit-surprise
  Using cached scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: joblib>=1.2.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (1.14.1)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml): started
  Building wheel for scikit-surprise (pyproject.toml): finished with status 'error'
Failed to build scikit-surprise

  error: subprocess-exited-with-error

  × Building wheel for scikit-surprise (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-312\surprise
      copying surprise\accuracy.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\builtin_datasets.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dataset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dump.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\reader.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\trainset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\utils.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__init__.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__main__.py -> build\lib.win-amd64-cpython-312\surprise
      creating build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\search.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\split.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\validation.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\__init__.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      creating build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running egg_info
      writing scikit_surprise.egg-info\PKG-INFO
      writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
      writing entry points to scikit_surprise.egg-info\entry_points.txt
      writing requirements to scikit_surprise.egg-info\requires.txt
      writing top-level names to scikit_surprise.egg-info\top_level.txt
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.so' found under directory 'surprise'
      adding license file 'LICENSE.md'
      writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-8s3zzz_q\overlay\Lib\site-packages\setuptools\command\build_py.py:212: _Warning: Package 'surprise.prediction_algorithms' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'surprise.prediction_algorithms' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'surprise.prediction_algorithms' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'surprise.prediction_algorithms' to be distributed and are
              already explicitly excluding 'surprise.prediction_algorithms' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying surprise\similarities.c -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\similarities.pyx -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running build_ext
      building 'surprise.similarities' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-surprise
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-surprise)

In [7]:
pip install pipwin

Collecting pipwin
  Downloading pipwin-0.5.2.tar.gz (7.9 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting docopt (from pipwin)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: requests in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from pipwin) (2.32.3)
Collecting pyprind (from pipwin)
  Downloading PyPrind-2.11.3-py2.py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: six in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from pipwin) (1.16.0)
Collecting beautifulsoup4>=4.9.0 (from pipwin)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting js2py (from pipwin)
  Downloading Js2Py-0.74-py3-none-any.whl.metadata (868 bytes)
Requirement already satisfied: packaging in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from pipwin) (24.2)
Collecting pySmartDL>=1.3.1 (from pipwin)
  Downloading pySmartDL-1.3.4-py3-none-any.whl.metadata (2.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.9.0->pipwin)
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Collecting tzlocal>=1.2 (from js2py->pipwin)
  Downloading tzlocal-5.2-py3-none-any.whl.metadata (7.8 kB)
Collecting pyjsparser>=2.5.1 (from js2py->pipwin)
  Downloading pyjsparser-2.7.1.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from requests->pipwin) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from requests->pipwin) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from requests->pipwin) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from requests->pipwin) (2024.8.30)
Requirement already satisfied: tzdata in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from tzlocal>=1.2->js2py->pipwin) (2024.2)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Downloading pySmartDL-1.3.4-py3-none-any.whl (20 kB)
Downloading Js2Py-0.74-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 24.9 MB/s eta 0:00:00
Downloading PyPrind-2.11.3-py2.py3-none-any.whl (8.4 kB)
Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Building wheels for collected packages: pipwin, docopt, pyjsparser
  Building wheel for pipwin (pyproject.toml): started
  Building wheel for pipwin (pyproject.toml): finished with status 'done'
  Created wheel for pipwin: filename=pipwin-0.5.2-py2.py3-none-any.whl size=8797 sha256=cbf71d6d371d3b0a6d93d3a041a6731c259c6dde267d9d0e52edd62c59e4a67f
  Stored in directory: c:\users\b.vivanco\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\e8\b5\1d\b94f69a230c016fe50ed36399dec48b34b82a11e4f344e9ccb
  Building wheel for docopt (pyproject.toml): started
  Building wheel for docopt (pyproject.toml): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13776 sha256=d9e9497becaed29ddb3bda456389c5cac99db5cbf0214f1e82bc412ec99aff13
  Stored in directory: c:\users\b.vivanco\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\1a\bf\a1\4cee4f7678c68c5875ca89eaccf460593539805c3906722228
  Building wheel for pyjsparser (pyproject.toml): started
  Building wheel for pyjsparser (pyproject.toml): finished with status 'done'
  Created wheel for pyjsparser: filename=pyjsparser-2.7.1-py3-none-any.whl size=25986 sha256=3aa2ead592d1147f4d17d454236fbfcc0c8cb62312cd803c7bdbe7d2833c0b3d
  Stored in directory: c:\users\b.vivanco\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\14\32\1d\9ef7b582e358446aeef4b9052aa89ef4dffa1688c1aae8aa13
Successfully built pipwin docopt pyjsparser
Installing collected packages: pySmartDL, pyprind, pyjsparser, docopt, tzlocal, soupsieve, js2py, beautifulsoup4, pipwin
Successfully installed beautifulsoup4-4.12.3 docopt-0.6.2 js2py-0.74 pipwin-0.5.2 pySmartDL-1.3.4 pyjsparser-2.7.1 pyprind-2.11.3 soupsieve-2.6 tzlocal-5.2
Note: you may need to restart the kernel to use updated packages.

In [9]:
pipwin install scikit-learn

SyntaxError: invalid syntax (485663659.py, line 1)

In [10]:
pip install scikit-surprise

Collecting scikit-surprise
  Using cached scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: joblib>=1.2.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-surprise) (1.14.1)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml): started
  Building wheel for scikit-surprise (pyproject.toml): finished with status 'error'
Failed to build scikit-surprise
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Building wheel for scikit-surprise (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-312\surprise
      copying surprise\accuracy.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\builtin_datasets.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dataset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\dump.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\reader.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\trainset.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\utils.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__init__.py -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\__main__.py -> build\lib.win-amd64-cpython-312\surprise
      creating build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\search.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\split.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\validation.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      copying surprise\model_selection\__init__.py -> build\lib.win-amd64-cpython-312\surprise\model_selection
      creating build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running egg_info
      writing scikit_surprise.egg-info\PKG-INFO
      writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
      writing entry points to scikit_surprise.egg-info\entry_points.txt
      writing requirements to scikit_surprise.egg-info\requires.txt
      writing top-level names to scikit_surprise.egg-info\top_level.txt
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.so' found under directory 'surprise'
      adding license file 'LICENSE.md'
      writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      C:\Users\b.vivanco\AppData\Local\Temp\pip-build-env-yvl9cnp3\overlay\Lib\site-packages\setuptools\command\build_py.py:212: _Warning: Package 'surprise.prediction_algorithms' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'surprise.prediction_algorithms' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'surprise.prediction_algorithms' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'surprise.prediction_algorithms' to be distributed and are
              already explicitly excluding 'surprise.prediction_algorithms' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying surprise\similarities.c -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\similarities.pyx -> build\lib.win-amd64-cpython-312\surprise
      copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-cpython-312\surprise\prediction_algorithms
      running build_ext
      building 'surprise.similarities' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-surprise
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-surprise)

In [16]:
pip install numpy

Requirement already satisfied: numpy in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [15]:
pip install git

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git

In [13]:
git clone https://github.com/NicolasHug/surprise.git

SyntaxError: invalid syntax (2887348544.py, line 1)

In [ ]:
cd surprise
python setup.py install

In [ ]:
pip list

Package            VersionNote: you may need to restart the kernel to use updated packages.

------------------ -----------
asttokens          2.4.1
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
comm               0.2.2
debugpy            1.8.8
decorator          5.1.1
executing          2.1.0
Faker              33.0.0
idna               3.10
imageio            2.36.0
ipykernel          6.29.5
ipython            8.29.0
jedi               0.19.2
joblib             1.4.2
jupyter_client     8.6.3
jupyter_core       5.7.2
lazy_loader        0.4
matplotlib-inline  0.1.7
nest-asyncio       1.6.0
networkx           3.4.2
numpy              2.1.3
packaging          24.2
pandas             2.2.3
parso              0.8.4
pillow             11.0.0
pip                24.3.1
platformdirs       4.3.6
prompt_toolkit     3.0.48
psutil             6.1.0
pure_eval          0.2.3
Pygments           2.18.0
python-dateutil    2.9.0.post0
pytz               2024.2
pywin32            308
pyzmq              26.2.0
requests           2.32.3
scikit-image       0.25.0rc1
scipy              1.14.1
six                1.16.0
stack-data         0.6.3
tifffile           2024.9.20
tornado            6.4.1
traitlets          5.14.3
typing_extensions  4.12.2
tzdata             2024.2
urllib3            2.2.3
wcwidth            0.2.13

# Sistema Recomendador

In [18]:
import pandas as pd

In [27]:
pd.set_option('display.max_colwidth', None)

In [109]:
df_globers = pd.read_csv('output-data-sintetica\skills_data-25-11-2024_18_28_43_342293.csv')
df_globers.head()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\b.vivanco\AppData\Local\Temp\ipykernel_22192\1697533416.py:1: SyntaxWarning: invalid escape sequence '\s'
  df_globers = pd.read_csv('output-data-sintetica\skills_data-25-11-2024_18_28_43_342293.csv')

,nombre,apellido,codigo,pais,rol,seniority,skills
0,Jaclyn,Stanley,79218551,Peru,Java Developer,ssr,"{'hard': ['Docker: 2', 'Data Access Layer: 1', 'Performance Tuning: 2', 'XML: 1', 'Data Structures: 2'], 'soft': ['Emotional Intelligence: 1', 'Interpersonal Communication: 2', 'Customer Service: 2', 'Writing Skills: 2', 'Influencing: 2']}"
1,Jennifer,Ortiz,80201916,Mexico,IOT Platform Engineer,jr,"{'hard': ['Device Connectivity: 1', 'Data Analytics: 1', 'IoT Protocols (MQTT, CoAP): 1', 'Testing and Validation: 1', 'User Interface Design: 1'], 'soft': ['Negotiation: 1', 'Writing Skills: 1', 'Mentoring Skills: 1', 'Adaptability to Change: 1', 'Networking Skills: 1']}"
2,Holly,Watson,32079276,Colombia,Web Mobile Developer,ssr,"{'hard': ['GraphQL: 2', 'React Native: 2', 'HTML: 1', 'Continuous Integration/Continuous Deployment (CI/CD): 2', 'Version Control: 2'], 'soft': ['Social Intelligence: 2', 'Integrity: 1', 'Negotiation Tactics: 1', 'Time Optimization: 1', 'Presentation Skills: 1']}"
3,Donald,Brown,29341234,Venezuela,Ruby Developer,jr,"{'hard': ['Deployment Techniques: 1', 'Ruby: 1', 'Object-Oriented Programming: 1', 'REST APIs: 1', 'Data Migration: 1'], 'soft': ['Social Skills: 1', 'Critical Observation: 1', 'Adaptability to Change: 1', 'Feedback Acceptance: 1', 'Ethical Judgment: 1']}"
4,Robert,Wagner,21992168,Uruguay,Cobol Developer,sr1,"{'hard': ['Reporting: 2', 'Data Warehousing: 2', 'VSAM: 3', 'Batch Processing: 2', 'User Acceptance Testing (UAT): 1', 'System Integration: 1', 'COBOL: 3', 'Data Migration: 3', 'SoftTech: 3', 'Business Logic: 2'], 'soft': ['Facilitation Skills: 1', 'Emotional Intelligence: 1', 'Persuasion: 1', 'Positivity: 2', 'Diversity Awareness: 1', 'Resourcefulness: 1', 'Writing Skills: 2', 'Trust Building: 1', 'Flexibility: 1', 'Self-Regulation: 1', 'Public Relations: 1', 'Situational Awareness: 1']}"

In [41]:
display(df_globers.head(1))

,nombre,apellido,codigo,pais,rol,seniority,skills
0,Jaclyn,Stanley,79218551,Peru,Java Developer,ssr,"{'hard': ['Docker: 2', 'Data Access Layer: 1', 'Performance Tuning: 2', 'XML: 1', 'Data Structures: 2'], 'soft': ['Emotional Intelligence: 1', 'Interpersonal Communication: 2', 'Customer Service: 2', 'Writing Skills: 2', 'Influencing: 2']}"

## Pre-precesamiento

### Transformar skills en una Matriz

In [42]:
df_globers.columns

Index(['nombre', 'apellido', 'codigo', 'pais', 'rol', 'seniority', 'skills'], dtype='object')

In [119]:
def skills_to_vector(row):
    hard_skills = eval(row['skills'])['hard']  # Usar eval para convertir la cadena a diccionario
    soft_skills = eval(row['skills'])['soft']
    
    # Crear un diccionario de habilidades y puntuaciones
    skill_dict = {}
    
    # Procesar habilidades duras
    for skill in hard_skills:
        skill_name, score = skill.split(': ')
        skill_dict[skill_name.strip()] = int(score.strip())
    
    # Procesar habilidades blandas
    for skill in soft_skills:
        skill_name, score = skill.split(': ')
        skill_dict[skill_name.strip()] = int(score.strip())
    
    return pd.Series(skill_dict)

# Aplicar la función al DataFrame
skills_matrix = df_globers.apply(skills_to_vector, axis=1).fillna(0)

# Mostrar la matriz de habilidades
print(skills_matrix.head())

   .NET Core  .NET Framework  3D Modeling  AI Programming  API Development  \
0        0.0             0.0          0.0             0.0              0.0
1        0.0             0.0          0.0             0.0              0.0
2        0.0             0.0          0.0             0.0              0.0
3        0.0             0.0          0.0             0.0              0.0
4        0.0             0.0          0.0             0.0              0.0

   API Management  API Testing  APIs  ASP.NET  AWS  ...  Work-Life Balance  \
0             0.0          0.0   0.0      0.0  0.0  ...                0.0
1             0.0          0.0   0.0      0.0  0.0  ...                0.0
2             0.0          0.0   0.0      0.0  0.0  ...                0.0
3             0.0          0.0   0.0      0.0  0.0  ...                0.0
4             0.0          0.0   0.0      0.0  0.0  ...                0.0

   Workflow Automation  Workflow Design  Workflows  \
0                  0.0              0.0        0.0
1                  0.0              0.0        0.0
2                  0.0              0.0        0.0
3                  0.0              0.0        0.0
4                  0.0              0.0        0.0

   Workplace Culture Awareness  Writing Skills  XML  Xcode  iCloud  iOS SDK
0                          0.0             2.0  1.0    0.0     0.0      0.0
1                          0.0             1.0  0.0    0.0     0.0      0.0
2                          0.0             0.0  0.0    0.0     0.0      0.0
3                          0.0             0.0  0.0    0.0     0.0      0.0
4                          0.0             2.0  0.0    0.0     0.0      0.0

[5 rows x 581 columns]

In [118]:
skills_matrix.columns

Index(['.NET Core', '.NET Framework', '3D Modeling', 'AI Programming',
       'API Development', 'API Management', 'API Testing', 'APIs', 'ASP.NET',
       'AWS',
       ...
       'Work-Life Balance', 'Workflow Automation', 'Workflow Design',
       'Workflows', 'Workplace Culture Awareness', 'Writing Skills', 'XML',
       'Xcode', 'iCloud', 'iOS SDK'],
      dtype='object', length=581)

In [138]:
skills_matrix.groupby('.NET Core').size()

for col in skills_matrix.columns:
    groupBy_df = skills_matrix.groupby(col).size()
    print(f'group by: {groupBy_df}')

group by: .NET Core
0.0    990
1.0      4
2.0      3
3.0      1
4.0      1
5.0      1
dtype: int64
group by: .NET Framework
0.0    988
1.0      4
2.0      2
3.0      1
4.0      4
5.0      1
dtype: int64
group by: 3D Modeling
0.0    991
1.0      4
2.0      2
3.0      2
5.0      1
dtype: int64
group by: AI Programming
0.0    986
1.0      5
2.0      6
3.0      2
4.0      1
dtype: int64
group by: API Development
0.0    915
1.0     25
2.0     30
3.0     17
4.0     10
5.0      3
dtype: int64
group by: API Management
0.0    978
1.0      6
2.0      6
3.0      3
4.0      5
5.0      2
dtype: int64
group by: API Testing
0.0    992
1.0      3
2.0      2
3.0      2
4.0      1
dtype: int64
group by: APIs
0.0    987
1.0      5
2.0      1
3.0      3
4.0      4
dtype: int64
group by: ASP.NET
0.0    973
1.0     10
2.0      6
3.0      5
4.0      4
5.0      2
dtype: int64
group by: AWS
0.0    959
1.0      8
2.0     13
3.0     10
4.0      7
5.0      3
dtype: int64
group by: Accessibility Features
0.0    977
1.0      4
2.0      8
3.0      5
4.0      5
5.0      1
dtype: int64
group by: Accessibility Standards
0.0    976
1.0      9
2.0      5
3.0      3
4.0      4
5.0      3
dtype: int64
group by: Active Listening
0.0    899
1.0     27
2.0     24
3.0     25
4.0     17
5.0      8
dtype: int64
group by: Active Record
0.0    990
1.0      3
2.0      2
3.0      2
4.0      3
dtype: int64
group by: Adaptability
0.0    912
1.0     29
2.0     25
3.0     16
4.0     12
5.0      6
dtype: int64
group by: Adaptability to Change
0.0    921
1.0     28
2.0     23
3.0     16
4.0      7
5.0      5
dtype: int64
group by: Agile
0.0    759
1.0     79
2.0     72
3.0     48
4.0     33
5.0      9
dtype: int64
group by: Algorithms
0.0    957
1.0     13
2.0     13
3.0     11
4.0      2
5.0      4
dtype: int64
group by: Analytical Thinking
0.0    916
1.0     27
2.0     22
3.0     18
4.0     10
5.0      7
dtype: int64
group by: Analytics Integration
0.0    973
1.0      7
2.0     13
3.0      4
4.0      1
5.0      2
dtype: int64
group by: Android Architecture Components
0.0    986
1.0      5
2.0      1
3.0      4
4.0      3
5.0      1
dtype: int64
group by: Android Jetpack
0.0    987
1.0      4
2.0      4
3.0      4
4.0      1
dtype: int64
group by: Android NDK
0.0    992
1.0      3
2.0      2
3.0      2
5.0      1
dtype: int64
group by: Android SDK
0.0    987
1.0      2
2.0      3
3.0      3
4.0      3
5.0      2
dtype: int64
group by: Angular
0.0    990
1.0      1
2.0      4
3.0      2
5.0      3
dtype: int64
group by: Animation
0.0    975
1.0      8
2.0      9
3.0      3
4.0      3
5.0      2
dtype: int64
group by: Animations
0.0    981
1.0      5
2.0      8
3.0      3
4.0      2
5.0      1
dtype: int64
group by: Apache Kafka
0.0    989
1.0      2
2.0      4
3.0      3
4.0      2
dtype: int64
group by: Apache Spark
0.0    987
1.0      2
2.0      5
3.0      3
4.0      1
5.0      2
dtype: int64
group by: App Deployment
0.0    988
1.0      1
2.0      2
3.0      4
4.0      2
5.0      3
dtype: int64
group by: App Store Submission
0.0    988
1.0      4
2.0      2
3.0      3
4.0      1
5.0      2
dtype: int64
group by: Appium
0.0    994
1.0      1
2.0      2
3.0      1
4.0      2
dtype: int64
group by: Application Development
0.0    993
1.0      2
2.0      1
3.0      2
4.0      1
5.0      1
dtype: int64
group by: Application Hardening
0.0    991
1.0      4
2.0      2
3.0      3
dtype: int64
group by: Application Lifecycle Management
0.0    993
3.0      3
4.0      4
dtype: int64
group by: Application Networking
0.0    983
1.0      4
2.0      3
3.0      7
4.0      3
dtype: int64
group by: Application Performance Monitoring (APM)
0.0    989
1.0      4
2.0      1
3.0      4
4.0      2
dtype: int64
group by: Application Security
0.0    982
1.0      3
2.0      5
3.0      6
4.0      2
5.0      2
dtype: int64
group by: Asset Management
0.0    987
1.0      5
2.0      3
3.0      4
5.0      1
dtype: int64
group by: Asynchronous Programming
0.0    979
1.0      7
2.0      9
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Attention to Detail
0.0    917
1.0     21
2.0     17
3.0     27
4.0     11
5.0      7
dtype: int64
group by: Authentication Mechanisms
0.0    979
1.0     13
2.0      2
3.0      5
4.0      1
dtype: int64
group by: Authenticity
0.0    907
1.0     27
2.0     24
3.0     14
4.0     15
5.0     13
dtype: int64
group by: Auto Layout
0.0    987
1.0      2
2.0      2
3.0      3
4.0      3
5.0      3
dtype: int64
group by: Automated Testing
0.0    989
1.0      4
2.0      1
3.0      5
5.0      1
dtype: int64
group by: Automation Anywhere
0.0    990
1.0      3
2.0      2
3.0      2
4.0      2
5.0      1
dtype: int64
group by: Automation Strategy
0.0    988
1.0      3
2.0      4
3.0      3
4.0      2
dtype: int64
group by: Automation Tools
0.0    975
1.0      8
2.0     10
3.0      3
4.0      3
5.0      1
dtype: int64
group by: Azure
0.0    983
1.0      5
2.0      1
3.0      4
4.0      6
5.0      1
dtype: int64
group by: Backup Strategies
0.0    987
1.0      4
2.0      6
3.0      2
5.0      1
dtype: int64
group by: Backup and Recovery
0.0    977
1.0      8
2.0      6
3.0      3
4.0      4
5.0      2
dtype: int64
group by: Batch Processing
0.0    986
1.0      2
2.0      4
3.0      4
4.0      2
5.0      2
dtype: int64
group by: Behavior-Driven Development (BDD)
0.0    993
1.0      2
2.0      3
3.0      2
dtype: int64
group by: Big Data Technologies
0.0    976
1.0      7
2.0      6
3.0      7
4.0      1
5.0      3
dtype: int64
group by: Blue Prism
0.0    987
1.0      3
2.0      4
3.0      1
4.0      1
5.0      4
dtype: int64
group by: Boost Library
0.0    988
1.0      5
2.0      1
3.0      3
4.0      3
dtype: int64
group by: Business Intelligence
0.0    978
1.0      9
2.0      7
3.0      3
4.0      2
5.0      1
dtype: int64
group by: Business Intelligence Tools
0.0    980
1.0      3
2.0      3
3.0      6
4.0      3
5.0      5
dtype: int64
group by: Business Logic
0.0    988
1.0      1
2.0      5
3.0      3
5.0      3
dtype: int64
group by: Business Process Automation
0.0    984
1.0      5
2.0      9
3.0      1
4.0      1
dtype: int64
group by: Business Process Mapping
0.0    987
1.0      3
2.0      4
3.0      4
4.0      2
dtype: int64
group by: C#
0.0    965
1.0     11
2.0     11
3.0      7
4.0      5
5.0      1
dtype: int64
group by: C++
0.0    987
1.0      4
2.0      4
3.0      2
4.0      2
5.0      1
dtype: int64
group by: CI/CD
0.0    960
1.0      9
2.0      9
3.0     11
4.0      8
5.0      3
dtype: int64
group by: CICS
0.0    991
2.0      3
3.0      2
4.0      2
5.0      2
dtype: int64
group by: CMake
0.0    989
1.0      2
2.0      1
3.0      3
4.0      4
5.0      1
dtype: int64
group by: COBOL
0.0    988
1.0      2
2.0      4
3.0      6
dtype: int64
group by: CSS
0.0    949
1.0     12
2.0     14
3.0     14
4.0     10
5.0      1
dtype: int64
group by: CSS Preprocessors (Sass, LESS)
0.0    987
1.0      4
2.0      2
3.0      2
4.0      3
5.0      2
dtype: int64
group by: Caching Techniques
0.0    977
1.0      8
2.0      6
3.0      4
4.0      4
5.0      1
dtype: int64
group by: Chai
0.0    990
1.0      1
2.0      4
3.0      3
4.0      2
dtype: int64
group by: Change Facilitation
0.0    930
1.0     18
2.0     16
3.0     18
4.0     12
5.0      6
dtype: int64
group by: Change Management
0.0    873
1.0     38
2.0     34
3.0     31
4.0     18
5.0      6
dtype: int64
group by: Change Sets
0.0    991
1.0      6
3.0      2
4.0      1
dtype: int64
group by: Civic Engagement
0.0    907
1.0     26
2.0     25
3.0     20
4.0     13
5.0      9
dtype: int64
group by: Civic Responsibility
0.0    913
1.0     22
2.0     25
3.0     17
4.0     16
5.0      7
dtype: int64
group by: Client Interaction
0.0    984
1.0      5
2.0      7
3.0      4
dtype: int64
group by: Client Management
0.0    907
1.0     33
2.0     24
3.0     18
4.0     12
5.0      6
dtype: int64
group by: Cloud Architecture
0.0    993
1.0      2
2.0      1
3.0      3
5.0      1
dtype: int64
group by: Cloud Computing
0.0    987
1.0      4
2.0      4
3.0      4
4.0      1
dtype: int64
group by: Cloud Data Solutions (AWS, Azure, GCP)
0.0    984
1.0      5
2.0      3
3.0      6
4.0      1
5.0      1
dtype: int64
group by: Cloud Migration
0.0    995
1.0      3
2.0      1
4.0      1
dtype: int64
group by: Cloud Platforms (AWS IoT, Azure IoT)
0.0    989
1.0      2
2.0      5
3.0      2
4.0      1
5.0      1
dtype: int64
group by: Cloud Security
0.0    965
1.0      8
2.0      9
3.0      8
4.0      1
5.0      9
dtype: int64
group by: Cloud Services
0.0    969
1.0      4
2.0      6
3.0     12
4.0      5
5.0      4
dtype: int64
group by: Cloud Services (Azure)
0.0    990
1.0      4
2.0      3
3.0      1
4.0      1
5.0      1
dtype: int64
group by: Cloud Testing
0.0    988
1.0      4
2.0      2
3.0      4
4.0      1
5.0      1
dtype: int64
group by: Coaching
0.0    902
1.0     26
2.0     21
3.0     26
4.0     16
5.0      9
dtype: int64
group by: Cocoa Touch
0.0    990
1.0      1
2.0      5
3.0      1
4.0      1
5.0      2
dtype: int64
group by: Code Refactoring
0.0    991
1.0      3
2.0      2
3.0      3
5.0      1
dtype: int64
group by: Code Review
0.0    968
1.0      9
2.0     10
3.0      6
4.0      4
5.0      3
dtype: int64
group by: Cognitive Flexibility
0.0    906
1.0     31
2.0     23
3.0     22
4.0     11
5.0      7
dtype: int64
group by: Collaboration
0.0    915
1.0     25
2.0     26
3.0     17
4.0      9
5.0      8
dtype: int64
group by: Collaboration Tools
0.0    993
1.0      1
2.0      4
3.0      1
4.0      1
dtype: int64
group by: Color Theory
0.0    986
1.0      4
2.0      5
3.0      1
5.0      4
dtype: int64
group by: Command Line Interface (CLI)
0.0    988
1.0      2
2.0      5
3.0      2
4.0      2
5.0      1
dtype: int64
group by: Communication
0.0    905
1.0     27
2.0     29
3.0     26
4.0      8
5.0      5
dtype: int64
group by: Community Cloud
0.0    983
1.0      5
2.0      5
3.0      3
4.0      4
dtype: int64
group by: Compiler Optimization
0.0    989
1.0      2
2.0      3
3.0      2
4.0      2
5.0      2
dtype: int64
group by: Compliance Standards (ISO, NIST)
0.0    991
1.0      2
2.0      3
3.0      2
4.0      2
dtype: int64
group by: Composer
0.0    982
1.0      7
2.0      2
3.0      4
4.0      4
5.0      1
dtype: int64
group by: Concurrency
0.0    975
1.0     10
2.0      8
3.0      3
4.0      4
dtype: int64
group by: Configuration Management
0.0    980
1.0      6
2.0      3
3.0      5
4.0      4
5.0      2
dtype: int64
group by: Conflict Management
0.0    913
1.0     25
2.0     22
3.0     23
4.0     12
5.0      5
dtype: int64
group by: Conflict Resolution
0.0    919
1.0     24
2.0     23
3.0     17
4.0     11
5.0      6
dtype: int64
group by: Constraint Layout
0.0    987
1.0      2
2.0      5
3.0      5
4.0      1
dtype: int64
group by: Containerization
0.0    992
1.0      2
2.0      1
3.0      3
4.0      2
dtype: int64
group by: Content Management
0.0    990
1.0      5
2.0      2
3.0      1
4.0      1
5.0      1
dtype: int64
group by: Content Management Systems (CMS)
0.0    988
1.0      6
2.0      2
3.0      3
5.0      1
dtype: int64
group by: Continuous Improvement
0.0    992
1.0      2
3.0      3
4.0      1
5.0      2
dtype: int64
group by: Continuous Integration
0.0    948
1.0     15
2.0     19
3.0      8
4.0      6
5.0      4
dtype: int64
group by: Continuous Integration/Continuous Deployment (CI/CD)
0.0    983
1.0      8
2.0      5
3.0      3
5.0      1
dtype: int64
group by: Continuous Testing
0.0    989
1.0      4
2.0      2
3.0      1
4.0      3
5.0      1
dtype: int64
group by: Core Animation
0.0    986
1.0      3
2.0      2
3.0      5
4.0      3
5.0      1
dtype: int64
group by: Core Data
0.0    989
1.0      4
2.0      4
3.0      1
4.0      1
5.0      1
dtype: int64
group by: Core Location
0.0    991
1.0      1
2.0      3
3.0      2
4.0      3
dtype: int64
group by: Coroutines
0.0    996
2.0      2
3.0      1
4.0      1
dtype: int64
group by: Cost Optimization
0.0    987
1.0      3
2.0      4
3.0      1
4.0      3
5.0      2
dtype: int64
group by: Creativity
0.0    812
1.0     52
2.0     55
3.0     41
4.0     26
5.0     14
dtype: int64
group by: Crisis Communication
0.0    904
1.0     30
2.0     22
3.0     24
4.0     15
5.0      5
dtype: int64
group by: Crisis Management
0.0    926
1.0     13
2.0     21
3.0     17
4.0     15
5.0      8
dtype: int64
group by: Critical Observation
0.0    918
1.0     26
2.0     25
3.0     19
4.0     10
5.0      2
dtype: int64
group by: Critical Thinking
0.0    917
1.0     23
2.0     25
3.0     16
4.0     12
5.0      7
dtype: int64
group by: Cross-Browser Compatibility
0.0    975
1.0     11
2.0      5
3.0      2
4.0      4
5.0      3
dtype: int64
group by: Cross-Browser Testing
0.0    993
1.0      3
2.0      1
3.0      2
4.0      1
dtype: int64
group by: Cross-Platform Development
0.0    978
1.0      3
2.0      7
3.0      7
4.0      1
5.0      4
dtype: int64
group by: Cross-platform Development
0.0    984
1.0      7
2.0      3
3.0      4
4.0      2
dtype: int64
group by: Cultural Awareness
0.0    895
1.0     25
2.0     26
3.0     22
4.0     20
5.0     12
dtype: int64
group by: Cultural Competence
0.0    903
1.0     28
2.0     20
3.0     21
4.0     20
5.0      8
dtype: int64
group by: Custom Objects
0.0    991
1.0      3
2.0      3
3.0      2
5.0      1
dtype: int64
group by: Custom Scripts
0.0    987
1.0      3
2.0      5
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Custom Web Parts
0.0    987
1.0      4
2.0      5
3.0      3
4.0      1
dtype: int64
group by: Custom Widgets
0.0    996
1.0      2
3.0      1
5.0      1
dtype: int64
group by: Customer Service
0.0    918
1.0     26
2.0     20
3.0     18
4.0     12
5.0      6
dtype: int64
group by: Cypress
0.0    993
1.0      2
2.0      1
3.0      1
4.0      1
5.0      2
dtype: int64
group by: DB2
0.0    988
1.0      3
2.0      4
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Dagger
0.0    991
1.0      3
2.0      1
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Dart
0.0    985
1.0      2
2.0      5
3.0      5
4.0      2
5.0      1
dtype: int64
group by: Data Access Layer
0.0    986
1.0      1
2.0      6
3.0      6
4.0      1
dtype: int64
group by: Data Analysis
0.0    978
1.0      5
2.0      9
3.0      3
4.0      3
5.0      2
dtype: int64
group by: Data Analytics
0.0    987
1.0      5
2.0      6
3.0      2
dtype: int64
group by: Data Architecture
0.0    983
1.0      3
2.0      9
3.0      2
4.0      3
dtype: int64
group by: Data Binding
0.0    991
1.0      4
2.0      3
3.0      1
4.0      1
dtype: int64
group by: Data Cataloging
0.0    987
1.0      3
2.0      5
3.0      1
4.0      2
5.0      2
dtype: int64
group by: Data Engineering
0.0    986
1.0      3
2.0      5
3.0      1
4.0      3
5.0      2
dtype: int64
group by: Data Extraction
0.0    991
1.0      2
2.0      1
4.0      4
5.0      2
dtype: int64
group by: Data Governance
0.0    978
1.0      6
2.0      6
3.0      4
4.0      4
5.0      2
dtype: int64
group by: Data Integration Tools
0.0    985
1.0      5
2.0      2
3.0      3
4.0      1
5.0      4
dtype: int64
group by: Data Interpretation
0.0    914
1.0     30
2.0     24
3.0     19
4.0     10
5.0      3
dtype: int64
group by: Data Lakes
0.0    983
1.0      4
2.0      6
3.0      1
4.0      5
5.0      1
dtype: int64
group by: Data Loss Prevention (DLP)
0.0    989
1.0      5
2.0      1
3.0      2
5.0      3
dtype: int64
group by: Data Manipulation
0.0    991
1.0      2
2.0      4
4.0      1
5.0      2
dtype: int64
group by: Data Mapping
0.0    989
1.0      1
2.0      5
3.0      2
4.0      3
dtype: int64
group by: Data Migration
0.0    944
1.0     14
2.0     12
3.0     17
4.0      9
5.0      4
dtype: int64
group by: Data Mining
0.0    986
1.0      9
2.0      1
3.0      2
4.0      1
5.0      1
dtype: int64
group by: Data Modeling
0.0    964
1.0     10
2.0     14
3.0      4
4.0      6
5.0      2
dtype: int64
group by: Data Pipeline Development
0.0    988
1.0      3
2.0      5
3.0      1
4.0      3
dtype: int64
group by: Data Processing
0.0    981
1.0      8
2.0      4
3.0      4
4.0      2
5.0      1
dtype: int64
group by: Data Protection
0.0    986
1.0      3
2.0      1
3.0      5
4.0      3
5.0      2
dtype: int64
group by: Data Quality Assessment
0.0    990
1.0      6
2.0      1
4.0      1
5.0      2
dtype: int64
group by: Data Quality Management
0.0    963
1.0      9
2.0     12
3.0      5
4.0      6
5.0      5
dtype: int64
group by: Data Security
0.0    988
1.0      3
2.0      3
3.0      2
4.0      2
5.0      2
dtype: int64
group by: Data Storage Solutions
0.0    987
1.0      3
2.0      4
3.0      4
4.0      2
dtype: int64
group by: Data Structures
0.0    877
1.0     36
2.0     30
3.0     23
4.0     20
5.0     14
dtype: int64
group by: Data Transformation
0.0    981
1.0      6
2.0      7
3.0      4
4.0      2
dtype: int64
group by: Data Visualization
0.0    956
1.0     12
2.0     14
3.0      9
4.0      6
5.0      3
dtype: int64
group by: Data Visualization Tools (Tableau, Power BI)
0.0    983
1.0      4
2.0      5
3.0      3
4.0      4
5.0      1
dtype: int64
group by: Data Warehousing
0.0    963
1.0     12
2.0     13
3.0      6
4.0      4
5.0      2
dtype: int64
group by: Data-Driven Testing
0.0    994
1.0      1
2.0      2
3.0      1
4.0      2
dtype: int64
group by: Database Administration
0.0    985
1.0      6
2.0      4
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Database Design
0.0    947
1.0     11
2.0     16
3.0     14
4.0      8
5.0      4
dtype: int64
group by: Database Management
0.0    959
1.0     13
2.0      8
3.0     10
4.0      9
5.0      1
dtype: int64
group by: Debugging
0.0    808
1.0     57
2.0     53
3.0     44
4.0     19
5.0     19
dtype: int64
group by: Decision Making
0.0    902
1.0     25
2.0     32
3.0     19
4.0     12
5.0     10
dtype: int64
group by: Defect Tracking
0.0    993
1.0      2
2.0      3
3.0      1
5.0      1
dtype: int64
group by: Delegation
0.0    919
1.0     33
2.0     21
3.0     13
4.0      7
5.0      7
dtype: int64
group by: Dependency Injection
0.0    965
1.0     16
2.0      5
3.0      9
4.0      3
5.0      2
dtype: int64
group by: Dependency Management
0.0    996
1.0      1
3.0      2
5.0      1
dtype: int64
group by: Deployment Techniques
0.0    960
1.0     15
2.0      4
3.0     10
4.0      4
5.0      7
dtype: int64
group by: Design Patterns
0.0    952
1.0     15
2.0     15
3.0      7
4.0     10
5.0      1
dtype: int64
group by: Design Systems
0.0    985
1.0      2
2.0      4
4.0      6
5.0      3
dtype: int64
group by: DevOps
0.0    977
1.0      8
2.0      6
3.0      3
4.0      4
5.0      2
dtype: int64
group by: DevSecOps
0.0    987
1.0      4
2.0      2
3.0      3
5.0      4
dtype: int64
group by: Device Connectivity
0.0    989
1.0      3
2.0      3
3.0      3
4.0      1
5.0      1
dtype: int64
group by: Device Management
0.0    989
1.0      5
2.0      5
3.0      1
dtype: int64
group by: DirectX
0.0    984
1.0      5
2.0      4
3.0      3
4.0      1
5.0      3
dtype: int64
group by: Disaster Recovery
0.0    992
1.0      3
2.0      3
3.0      2
dtype: int64
group by: Disaster Recovery Planning
0.0    982
1.0      5
2.0      1
3.0      4
4.0      4
5.0      4
dtype: int64
group by: Diversity Awareness
0.0    919
1.0     28
2.0     25
3.0     16
4.0      6
5.0      6
dtype: int64
group by: Django
0.0    988
1.0      2
2.0      4
3.0      5
5.0      1
dtype: int64
group by: Docker
0.0    930
1.0     19
2.0     21
3.0     17
4.0      9
5.0      4
dtype: int64
group by: Document Libraries
0.0    994
2.0      2
3.0      3
4.0      1
dtype: int64
group by: Documentation
0.0    976
1.0      7
2.0      6
3.0      3
4.0      4
5.0      4
dtype: int64
group by: ETL
0.0    988
1.0      4
2.0      3
3.0      3
4.0      1
5.0      1
dtype: int64
group by: ETL Processes
0.0    985
1.0      5
2.0      5
3.0      3
5.0      2
dtype: int64
group by: Edge Computing
0.0    983
1.0      6
2.0      3
3.0      4
4.0      3
5.0      1
dtype: int64
group by: Embedded Systems
0.0    978
1.0      4
2.0      5
3.0      8
4.0      3
5.0      2
dtype: int64

In [112]:
type(skills_matrix)

pandas.core.frame.DataFrame

### Dividir dataset

In [142]:
pip install -U scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\b.vivanco\desktop\dev\globant_ai\mvp-env\lib\site-packages (from scikit-learn) (1.4.2)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------------------ --------------------- 5.0/11.0 MB 25.1 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 26.8 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 25.4 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scikit-learn
Successfully installed scikit-learn-1.5.2 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [143]:
from sklearn.model_selection import train_test_split
import numpy as np

# Crear una matriz de interacciones (simulación de puntuaciones)
interactions = np.random.randint(1, 6, size=skills_matrix.shape)  # Simulando puntuaciones entre 1 y 5

# Dividir en conjunto de entrenamiento y prueba
train_data, test_data = train_test_split(interactions, test_size=0.2, random_state=42)

### Implementar y entrenar Funk-SVD

In [ ]:
class FunkSVD:
    def __init__(self, n_factors=10, n_epochs=1000, lr=0.01, reg=0.02):
        self.n_factors = n_factors
        self.n_epochs = n_epochs
        self.lr = lr
        self.reg = reg

    def fit(self, train_data):
        n_users, n_items = train_data.shape
        self.user_factors = np.random.normal(scale=1./self.n_factors, size=(n_users, self.n_factors))
        self.item_factors = np.random.normal(scale=1./self.n_factors, size=(n_items, self.n_factors))

        for epoch in range(self.n_epochs):
            for i in range(n_users):
                for j in range(n_items):
                    if train_data[i][j] > 0:
                        error = train_data[i][j] - self.predict(i, j)
                        self.user_factors[i] += self.lr * (error * self.item_factors[j] - self.reg * self.user_factors[i])
                        self.item_factors[j] += self.lr * (error * self.user_factors[i] - self.reg * self.item_factors[j])

    def predict(self, user_id, item_id):
        return np.dot(self.user_factors[user_id], self.item_factors[item_id])

# Entrenamiento del modelo
model = FunkSVD(n_factors=10)
model.fit(train_data)

### Evaluar el modelo 🚀

In [ ]:
from sklearn.metrics import mean_squared_error

def evaluate_model(model, test_data):
    predictions = []
    actuals = []
    
    for i in range(test_data.shape[0]):
        for j in range(test_data.shape[1]):
            if test_data[i][j] > 0: 
                predictions.append(model.predict(i, j))
                actuals.append(test_data[i][j])
    
    rmse = np.sqrt(mean_squared_error(actuals, predictions))
    mae = np.mean(np.abs(np.array(predictions) - np.array(actuals)))
    
    return rmse, mae

rmse, mae = evaluate_model(model, test_data)
print(f"RMSE: {rmse}, MAE: {mae}")